// Code generated by goctl. DO NOT EDIT.
package types

type PayOrderRequest struct {
	MerchantOrderNo   string `json:"merchantOrderNo, optional"`
	OrderNo           string `json:"orderNo"`
	PayType           string `json:"payType, optional"`
	ChannelPayType    string `json:"channelPayType, optional"`
	TransactionAmount string `json:"transactionAmount"`
	BankCode          string `json:"bankCode, optional"`
	PageUrl           string `json:"pageUrl, optional"`
	OrderName         string `json:"orderName, optional"`
	MerchantId        string `json:"merchantId, optional"`
	Currency          string `json:"currency, optional"`
	SourceIp          string `json:"sourceIp, optional"`
	UserId            string `json:"userId, optional"`
	JumpType          string `json:"jumpType, optional"`
	PlayerId          string `json:"playerId, optional"`
	Address           string `json:"address, optionial"`
	City              string `json:"city, optionial"`
	ZipCode           string `json:"zipCode, optionial"`
	Country           string `json:"country, optionial"`
	Phone             string `json:"phone, optionial"`
	Email             string `json:"email, optionial"`
	PageFailedUrl     string `json:"pageFailedUrl, optional"`
}

type PayOrderResponse struct {
	PayPageInfo    string `json:"payPageInfo, optional"`
	PayPageType    string `json:"payPageType, optional"`
	ChannelOrderNo string `json:"channelOrderNo, optional"`
	OrderAmount    string `json:"orderAmount, optional"`
	RealAmount     string `json:"realAmount, optional"`
	Status         string `json:"status, optional"`
	IsCheckOutMer  bool   `json:"isCheckOutMer, optional"`
}

type PayOrderQueryRequest struct {
	OrderNo        string `json:"orderNo"`
	ChannelOrderNo string `json:"channelOrderNo, optional"`
}

type PayOrderQueryResponse struct {
	OrderStatus      string  `json:"orderStatus"`
	OrderAmount      float64 `json:"orderAmount"`
	ChannelOrderTime string  `json:"channelOrderTime"`
	ChannelCharge    float64 `json:"channelCharge"`
	CallBackStatus   string  `json:"callBackStatus"`
	OrderUpdateTime  string  `json:"orderUpdateTime"`
	ChannelOrderNo   string  `json:"channelOrderNo"`
}

type Empty struct {
}

type OrderResponse struct {
	Code    string      `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,optional"`
}

type PayQueryInternalBalanceResponse struct {
	ChannelNametring   string `json:"channelNametring"`
	ChannelCodingtring string `json:"channelCodingtring"`
	WithdrawBalance    string `json:"withdrawBalance"`
	ProxyPayBalance    string `json:"proxyPayBalance"`
	UpdateTimetring    string `json:"updateTimetring"`
	ErrorCodetring     string `json:"errorCodetring, optional"`
	ErrorMsgtring      string `json:"errorMsgtring, optional"`
}

type ProxyPayOrderRequest struct {
	MerchantOrderNo      string `json:"merchantOrderNo, optional"`
	MerchantId           string `json:"merchantId, optional"`
	OrderNo              string `json:"orderNo"`
	TransactionType      string `json:"transactionType"`
	TransactionAmount    string `json:"transactionAmount"`
	ReceiptAccountNumber string `json:"receiptAccountNumber"`
	ReceiptAccountName   string `json:"receiptAccountName"`
	ReceiptCardProvince  string `json:"receiptCardProvince"`
	ReceiptCardCity      string `json:"receiptCardCity"`
	ReceiptCardArea      string `json:"receiptCardArea"`
	ReceiptCardBranch    string `json:"receiptCardBranch"`
	ReceiptCardBankCode  string `json:"receiptCardBankCode"`
	ReceiptCardBankName  string `json:"receiptCardBankName"`
	PlayerId             string `json:"playerId, optional"`
	Currency             string `json:"currency, optional"` //加密货币渠道，需要填入换汇用的
	Remark               string `json:"remark, optional"`   //印度渠道需要填IFSC
}

type ProxyPayOrderResponse struct {
	ChannelOrderNo string `json:"channelOrderNo"`
	OrderStatus    string `json:"orderStatus"`
}

type ProxyPayOrderQueryRequest struct {
	OrderNo        string `json:"orderNo"` //渠道
	ChannelOrderNo string `json:"channelOrderNo"`
}

type ProxyPayOrderQueryResponse struct {
	Status           int     `json:"status"`
	ChannelOrderNo   string  `json:"channelOrderNo"`
	OrderStatus      string  `json:"orderStatus"`
	CallBackStatus   string  `json:"callBackStatus"`
	ChannelReplyDate string  `json:"channelReplyDate"`
	ChannelCharge    float64 `json:"channelCharge"`
}

type ProxyPayQueryInternalBalanceResponse struct {
	ChannelNametring   string `json:"channelNametring"`
	ChannelCodingtring string `json:"channelCodingtring"`
	WithdrawBalance    string `json:"withdrawBalance"`
	ProxyPayBalance    string `json:"proxyPayBalance"`
	UpdateTimetring    string `json:"updateTimetring"`
	ErrorCodetring     string `json:"errorCodetring"`
	ErrorMsgtring      string `json:"errorMsgtring"`
}

type ProxyPayCallBackRequest struct {
	Ip                string `json:"ip, optional"`
	Address           string `json:"address, optional"`
	Amount            string `json:"amount, optional"`
	ClientReferenceId string `json:"client_reference_id, optional"`
	Currency          string `json:"currency, optional"`
	CustomerEmail     string `json:"customer_email, optional"`
	Fee               string `json:"fee, optional"`
	FeeUsd            string `json:"fee_usd, optional"`
	FiatAmount        string `json:"fiat_amount, optional"`
	HashCode          string `json:"hash_code, optional"`
	Rates             string `json:"rates, optional"`
	Status            string `json:"status, optional"`
	Token             string `json:"token, optional"`
	TxHash            string `json:"tx_hash, optional"`
	Txid              string `json:"txid, optional"`
}

type PayCallBackRequest struct {
	MyIp              string      `json:"myIp, optional, optional"`
	ClientReferenceId interface{} `json:"client_reference_id, optional"`
	Customer          string      `json:"customer, optional"`
	CustomerEmail     interface{} `json:"customer_email, optional"`
	DirepayId         int         `json:"direpay_id, optional"`
	EnablePromotion   bool        `json:"enable_promotion, optional"`
	HashCode          string      `json:"hash_code, optional"`
	InvoiceAmount     float64     `json:"invoice_amount, optional"`
	InvoiceCurrency   string      `json:"invoice_currency, optional"`
	PaidAmount        string      `json:"paid_amount, optional"` //BigCatPay实际收到的加密金额
	PaidFiat          string      `json:"paid_fiat, optional"`   //BigCatPay实际收到的法币金额
	//LineItems         []struct {
	//	Name        string      `json:"name, optional"`
	//	ItemId      string      `json:"item_id, optional"`
	//	Description string      `json:"description, optional"`
	//	Amount      float64     `json:"amount, optional"`
	//	Quantity    interface{} `json:"quantity, optional"`
	//} `json:"line_items, optional"`
	PaymentAmount string `json:"payment_amount, optional"`
	PaymentToken  string `json:"payment_token, optional"`
	Rates         string `json:"rates, optional"`
	Status        string `json:"status, optional"`
	TxHash        string `json:"tx_hash, optional"`
	Txid          string `json:"txid, optional"`
}

type ReceiverInfoVO struct {
	CardName   string  `json:"cardName"`
	CardNumber string  `json:"cardNumber"`
	BankName   string  `json:"bankName"`
	BankBranch string  `json:"bankBranch"`
	Amount     float64 `json:"amount"`
	Link       string  `json:"link"`
	Remark     string  `json:"remark"`
}

type ReceiverInfoBTCVO struct {
	OrderNo         string  `json:"order_no"`
	CustomerUid     string  `json:"customer_uid"`
	InvoiceAmount   float64 `json:"invoice_amount"`
	InvoiceCurrency string  `json:"invoice_currency"`
	PaymentAmount   string  `json:"payment_amount"`
	PaymentToken    string  `json:"payment_token"`
	Rates           string  `json:"rates"`
	PaymentAddress  string  `json:"payment_address"`
}

type ExchangeInfo struct {
	Url          string `json:"url"`
	Token        string `json:"token"`         //加密货币
	CryptoAmount string `json:"crypto_amount"` //加密货币数额
	Currency     string `json:"currency"`      //法币
}

type Item struct {
	Name        string `json:"name"`
	ItemId      string `json:"item_id"`
	Description string `json:"description"`
	Amount      string `json:"amount"`
	Quantity    string `json:"quantity"`
}
