kind: pipeline
name: channel_app

clone:
  disable: true

steps:
  - name: docker-zhongshoupay
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - cd /root/channel_app
        - git checkout -- .
        - git checkout zhongshoupay
        - git pull origin zhongshoupay
        - go mod tidy
        - docker-compose -f zhongshoupay/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=zhongshoupay" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - docker build -t zhongshoupay -f zhongshoupay/Dockerfile .
        - docker-compose -f zhongshoupay/docker-compose.yml up -d
    when:
      branch:
        - zhongshoupay
      event:
        - push
trigger:
  branch:
    - zhongshoupay



---
kind: pipeline
name: lepay

clone:
  disable: true

steps:
  - name: docker-lepay
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - cd /root/channel_app
        - git checkout -- .
        - git checkout lepay
        - git pull origin lepay
        - go mod tidy
        - docker-compose -f lepay/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=lepay" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - docker build -t lepay -f lepay/Dockerfile .
        - docker-compose -f lepay/docker-compose.yml up -d
    when:
      branch:
        - zhongshoupay
      event:
        - push
trigger:
  branch:
    - zhongshoupay
