kind: pipeline
name: channel_app

clone:
  disable: true

steps:
  - name: docker-zhongshoupay
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - export PATH=$PATH:/usr/local/go/bin
        - cd /root/channel_app
        - git pull
        - git checkout stage
        - git checkout -- .
        - git pull origin stage
        - go mod tidy
        - docker-compose -f zhongshoupay/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=zhongshoupay" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/zhongshoupay zhongshoupay/zhongshoupay.go
        - docker build -t zhongshoupay -f zhongshoupay/Dockerfile .
        - docker-compose -f zhongshoupay/docker-compose.yml up -d
    when:
      branch:
        - stage
      event:
        - push


---
kind: pipeline
name: lepay

clone:
  disable: true

steps:
  - name: docker-lepay
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - export PATH=$PATH:/usr/local/go/bin
        - cd /root/channel_app
        - git pull
        - git checkout stage
        - git pull origin stage
        - go mod tidy
        - docker-compose -f lepay/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=lepay" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/lepay lepay/pay.go
        - docker build -t lepay -f lepay/Dockerfile .
        - docker-compose -f lepay/docker-compose.yml up -d
    when:
      branch:
        - stage
      event:
        - push


---
kind: pipeline
name: taotaopay

clone:
  disable: true

steps:
  - name: docker-taotaopay
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - export PATH=$PATH:/usr/local/go/bin
        - cd /root/channel_app
        - git pull 
        - git checkout stage
        - git pull origin stage
        - go mod tidy
        - docker-compose -f taotaopay/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=taotaopay" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/taotaopay taotaopay/pay.go
        - docker build -t taotaopay -f taotaopay/Dockerfile .
        - docker-compose -f taotaopay/docker-compose.yml up -d
    when:
      branch:
        - stage
      event:
        - push

---
kind: pipeline

name: wanlisinpay

clone:
  disable: true

steps:
  - name: docker-wanlisinpay
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - export PATH=$PATH:/usr/local/go/bin
        - cd /root/channel_app
        - git pull
        - git checkout stage 
        - git pull origin stage
        - go mod tidy
        - docker-compose -f wanlisinpay/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=wanlisinpay" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/wanlisinpay wanlisinpay/pay.go
        - docker build -t wanlisinpay -f wanlisinpay/Dockerfile .
        - docker-compose -f wanlisinpay/docker-compose.yml up -d
    when:
      branch:
        - stage
      event:
        - push

---
kind: pipeline
name: wangjhepay

clone:
  disable: true

steps:
  - name: docker-wangjhepay
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - export PATH=$PATH:/usr/local/go/bin
        - cd /root/channel_app
        - git pull
        - git checkout stage
        - git pull origin stage
        - go mod tidy
        - docker-compose -f wangjhepay/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=wangjhepay" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/wangjhepay wangjhepay/pay.go
        - docker build -t wangjhepay -f wangjhepay/Dockerfile .
        - docker-compose -f wangjhepay/docker-compose.yml up -d
    when:
      branch:
        - stage
      event:
        - push

---
kind: pipeline
name: shenfutongpay6

clone:
  disable: true

steps:
  - name: docker-shenfutongpay6
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - export PATH=$PATH:/usr/local/go/bin
        - cd /root/channel_app
        - git pull
        - git checkout stage
        - git pull origin stage
        - go mod tidy
        - docker-compose -f shenfutongpay6/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=shenfutongpay6" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/shenfutongpay6 shenfutongpay6/pay.go
        - docker build -t shenfutongpay6 -f shenfutongpay6/Dockerfile .
        - docker-compose -f shenfutongpay6/docker-compose.yml up -d
    when:
      branch:
        - stage
      event:
        - push

---
kind: pipeline
name: stpay

clone:
  disable: true

steps:
  - name: docker-stpay
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - export PATH=$PATH:/usr/local/go/bin
        - cd /root/channel_app
        - git pull
        - git checkout stpay
        - git pull origin stage
        - go mod tidy
        - docker-compose -f stpay/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=stpay" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/stpay stpay/pay.go
        - docker build -t stpay -f stpay/Dockerfile .
        - docker-compose -f stpay/docker-compose.yml up -d
    when:
      branch:
        - stage
      event:
        - push

---
kind: pipeline
name: ailefupay

clone:
  disable: true

steps:
  - name: docker-ailefupay
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - export PATH=$PATH:/usr/local/go/bin
        - cd /root/channel_app
        - git pull
        - git checkout stage
        - git pull origin stage
        - go mod tidy
        - docker-compose -f ailefupay/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=ailefupay" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/ailefupay ailefupay/pay.go
        - docker build -t ailefupay -f ailefupay/Dockerfile .
        - docker-compose -f ailefupay/docker-compose.yml up -d
    when:
      branch:
        - stage
      event:
        - push
