kind: pipeline
name: channel_app

clone:
  disable: true

steps:
  - name: docker-zhongshoupay
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - cd /root/channel_app
        - git checkout -- .
        - git checkout zhongshoupay
        - git checkout -- .
        - git pull origin zhongshoupay
        - go mod tidy
        - docker-compose -f zhongshoupay/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=zhongshoupay" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/zhongshoupay zhongshoupay/zhongshoupay.go
        - docker build -t zhongshoupay -f zhongshoupay/Dockerfile .
        - docker-compose -f zhongshoupay/docker-compose.yml up -d
    when:
      branch:
        - zhongshoupay
      event:
        - push
trigger:
  branch:
    - zhongshoupay
---
kind: pipeline
name: lepay

clone:
  disable: true

steps:
  - name: docker-lepay
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - cd /root/channel_app
        - git checkout -- .
        - git checkout lepay
        - git checkout -- .
        - git pull origin lepay
        - go mod tidy
        - docker-compose -f lepay/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=lepay" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/lepay lepay/pay.go
        - docker build -t lepay -f lepay/Dockerfile .
        - docker-compose -f lepay/docker-compose.yml up -d
    when:
      branch:
        - lepay
      event:
        - push
trigger:
  branch:
    - lepay
---
kind: pipeline
name: taotaopay

clone:
  disable: true

steps:
  - name: docker-taotaopay
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - cd /root/channel_app
        - git checkout -- .
        - git checkout taotaopay
        - git checkout -- .
        - git pull origin taotaopay
        - go mod tidy
        - docker-compose -f taotaopay/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=taotaopay" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/taotaopay taotaopay/pay.go
        - docker build -t taotaopay -f taotaopay/Dockerfile .
        - docker-compose -f taotaopay/docker-compose.yml up -d
    when:
      branch:
        - taotaopay
      event:
        - push
trigger:
  branch:
    - taotaopay
---
kind: pipeline
name: wanlisinpay

clone:
  disable: true

steps:
  - name: docker-wanlisinpay
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - cd /root/channel_app
        - git checkout -- .
        - git checkout wanlisinpay
        - git checkout -- .
        - git pull origin wanlisinpay
        - go mod tidy
        - docker-compose -f wanlisinpay/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=wanlisinpay" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/wanlisinpay wanlisinpay/pay.go
        - docker build -t wanlisinpay -f wanlisinpay/Dockerfile .
        - docker-compose -f wanlisinpay/docker-compose.yml up -d
    when:
      branch:
        - wanlisinpay
      event:
        - push
trigger:
  branch:
    - wanlisinpay
---
kind: pipeline
name: wangjhepay

clone:
  disable: true

steps:
  - name: docker-wangjhepay
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - cd /root/channel_app
        - git checkout -- .
        - git checkout wangjhepay
        - git checkout -- .
        - git pull origin wangjhepay
        - go mod tidy
        - docker-compose -f wangjhepay/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=wangjhepay" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/wangjhepay wangjhepay/pay.go
        - docker build -t wangjhepay -f wangjhepay/Dockerfile .
        - docker-compose -f wangjhepay/docker-compose.yml up -d
    when:
      branch:
        - wangjhepay
      event:
        - push
trigger:
  branch:
    - wangjhepay
---
kind: pipeline
name: shenfutongpay6

clone:
  disable: true

steps:
  - name: docker-shenfutongpay6
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - cd /root/channel_app
        - git checkout -- .
        - git checkout shenfutongpay6
        - git checkout -- .
        - git pull origin shenfutongpay6
        - go mod tidy
        - docker-compose -f shenfutongpay6/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=shenfutongpay6" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/shenfutongpay6 shenfutongpay6/pay.go
        - docker build -t shenfutongpay6 -f shenfutongpay6/Dockerfile .
        - docker-compose -f shenfutongpay6/docker-compose.yml up -d
    when:
      branch:
        - shenfutongpay6
      event:
        - push
trigger:
  branch:
    - shenfutongpay6
---
kind: pipeline
name: stpay

clone:
  disable: true

steps:
  - name: docker-stpay
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - cd /root/channel_app
        - git checkout -- .
        - git checkout stpay
        - git checkout -- .
        - git pull origin stpay
        - go mod tidy
        - docker-compose -f stpay/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=stpay" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/stpay stpay/pay.go
        - docker build -t stpay -f stpay/Dockerfile .
        - docker-compose -f stpay/docker-compose.yml up -d
    when:
      branch:
        - stpay
      event:
        - push
trigger:
  branch:
    - stpay
---
kind: pipeline
name: ailefupay

clone:
  disable: true

steps:
  - name: docker-ailefupay
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - cd /root/channel_app
        - git checkout -- .
        - git checkout ailefupay
        - git checkout -- .
        - git pull origin ailefupay
        - go mod tidy
        - docker-compose -f ailefupay/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=ailefupay" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/ailefupay ailefupay/pay.go
        - docker build -t ailefupay -f ailefupay/Dockerfile .
        - docker-compose -f ailefupay/docker-compose.yml up -d
    when:
      branch:
        - ailefupay
      event:
        - push
trigger:
  branch:
    - ailefupay
---
kind: pipeline
name: huanyupay

clone:
  disable: true

steps:
  - name: docker-huanyupay
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - cd /root/channel_app
        - git checkout -- .
        - git checkout huanyupay
        - git checkout -- .
        - git pull origin huanyupay
        - go mod tidy
        - docker-compose -f huanyupay/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=huanyupay" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/huanyupay huanyupay/pay.go
        - docker build -t huanyupay -f huanyupay/Dockerfile .
        - docker-compose -f huanyupay/docker-compose.yml up -d
    when:
      branch:
        - huanyupay
      event:
        - push
trigger:
  branch:
    - huanyupay
---
kind: pipeline
name: lyubupay

clone:
  disable: true

steps:
  - name: docker-lyubupay
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - cd /root/channel_app
        - git checkout -- .
        - git checkout lyubupay
        - git checkout -- .
        - git pull origin lyubupay
        - go mod tidy
        - docker-compose -f lyubupay/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=lyubupay" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/lyubupay lyubupay/pay.go
        - docker build -t lyubupay -f lyubupay/Dockerfile .
        - docker-compose -f lyubupay/docker-compose.yml up -d
    when:
      branch:
        - lyubupay
      event:
        - push
trigger:
  branch:
    - lyubupay
    
---
kind: pipeline
name: liepay

clone:
  disable: true

steps:
  - name: docker-liepay
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - cd /root/channel_app
        - git checkout -- .
        - git checkout liepay
        - git checkout -- .
        - git pull origin liepay
        - go mod tidy
        - docker-compose -f liepay/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=liepay" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/liepay liepay/pay.go
        - docker build -t liepay -f liepay/Dockerfile .
        - docker-compose -f liepay/docker-compose.yml up -d
    when:
      branch:
        - liepay
      event:
        - push
trigger:
  branch:
    - liepay

---
kind: pipeline
name: vcpay2

clone:
  disable: true

steps:
  - name: docker-vcpay2
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - cd /root/channel_app
        - git checkout -- .
        - git checkout vcpay2
        - git checkout -- .
        - git pull origin vcpay2
        - go mod tidy
        - docker-compose -f vcpay2/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=vcpay2" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/vcpay2 vcpay2/pay.go
        - docker build -t vcpay2 -f vcpay2/Dockerfile .
        - docker-compose -f vcpay2/docker-compose.yml up -d
    when:
      branch:
        - vcpay2
      event:
        - push
trigger:
  branch:
    - vcpay2

---
kind: pipeline
name: mlbproxypay2

clone:
  disable: true

steps:
  - name: docker-mlbproxypay2
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - cd /root/channel_app
        - git checkout -- .
        - git checkout mlbproxypay2
        - git checkout -- .
        - git pull origin mlbproxypay2
        - go mod tidy
        - docker-compose -f mlbproxypay2/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=mlbproxypay2" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/mlbproxypay2 mlbproxypay2/pay.go
        - docker build -t mlbproxypay2 -f mlbproxypay2/Dockerfile .
        - docker-compose -f mlbproxypay2/docker-compose.yml up -d
    when:
      branch:
        - mlbproxypay2
      event:
        - push
trigger:
  branch:
    - mlbproxypay2

