kind: pipeline
name: channel_app

clone:
  disable: true

steps:
  - name: docker-zhongshoupay
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - cd /root/channel_app
        - git checkout -- .
        - git checkout zhongshoupay
        - git checkout -- .
        - git pull origin zhongshoupay
        - go mod tidy
        - docker-compose -f zhongshoupay/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=zhongshoupay" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/zhongshoupay zhongshoupay/zhongshoupay.go
        - docker build -t zhongshoupay -f zhongshoupay/Dockerfile .
        - docker-compose -f zhongshoupay/docker-compose.yml up -d
    when:
      branch:
        - zhongshoupay
      event:
        - push


---
kind: pipeline
name: lepay

clone:
  disable: true

steps:
  - name: docker-lepay
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - cd /root/channel_app
        - git checkout -- .
        - git checkout lepay
        - git checkout -- .
        - git pull origin lepay
        - go mod tidy
        - docker-compose -f lepay/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=lepay" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/taotaopay taotaopay/pay.go
        - docker build -t lepay -f lepay/Dockerfile .
        - docker-compose -f lepay/docker-compose.yml up -d
    when:
      branch:
        - lepay
      event:
        - push


---
kind: pipeline
name: taotaopay

clone:
  disable: true

steps:
  - name: docker-taotaopay
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - cd /root/channel_app
        - git checkout -- .
        - git checkout taotaopay
        - git checkout -- .
        - git pull origin taotaopay
        - go mod tidy
        - docker-compose -f taotaopay/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=taotaopay" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/taotaopay taotaopay/pay.go
        - docker build -t taotaopay -f taotaopay/Dockerfile .
        - docker-compose -f taotaopay/docker-compose.yml up -d
    when:
      branch:
        - taotaopay
      event:
        - push

---
kind: pipeline
name: wanlisinpay

clone:
  disable: true

steps:
  - name: docker-wanlisinpay
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - cd /root/channel_app
        - git checkout -- .
        - git checkout wanlisinpay
        - git checkout -- .
        - git pull origin wanlisinpay
        - go mod tidy
        - docker-compose -f wanlisinpay/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=wanlisinpay" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/wanlisinpay wanlisinpay/pay.go
        - docker build -t wanlisinpay -f wanlisinpay/Dockerfile .
        - docker-compose -f wanlisinpay/docker-compose.yml up -d
    when:
      branch:
        - wanlisinpay
      event:
        - push

---
kind: pipeline
name: wangjhepay

clone:
  disable: true

steps:
  - name: docker-wangjhepay
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - cd /root/channel_app
        - git checkout -- .
        - git checkout wangjhepay
        - git checkout -- .
        - git pull origin wangjhepay
        - go mod tidy
        - docker-compose -f wangjhepay/docker-compose.yml down
        - docker rmi -f $(docker images --filter="reference=wangjhepay" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/wangjhepay wangjhepay/pay.go
        - docker build -t wangjhepay -f wangjhepay/Dockerfile .
        - docker-compose -f wangjhepay/docker-compose.yml up -d
    when:
      branch:
        - wangjhepay
      event:
        - push

