// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	txpay "github.com/copo888/channel_app/txpay/api/internal/handler/txpay"
	"github.com/copo888/channel_app/txpay/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/proxy-pay-call-back",
				Handler: txpay.ProxyPayCallBackHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
