// Code generated by protoc-gen-go. DO NOT EDIT.
// source: txpay.proto

package txpay

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//import "google/protobuf/empty.proto";
type Channel struct {
	Id                      int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                    string  `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name                    string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	IsProxy                 string  `protobuf:"bytes,4,opt,name=isProxy,proto3" json:"isProxy,omitempty"`
	IsNzPre                 string  `protobuf:"bytes,5,opt,name=isNzPre,proto3" json:"isNzPre,omitempty"`
	ApiUrl                  string  `protobuf:"bytes,6,opt,name=apiUrl,proto3" json:"apiUrl,omitempty"`
	CurrencyCode            string  `protobuf:"bytes,7,opt,name=currencyCode,proto3" json:"currencyCode,omitempty"`
	ChannelWithdrawCharge   float32 `protobuf:"fixed32,8,opt,name=channelWithdrawCharge,proto3" json:"channelWithdrawCharge,omitempty"`
	Balance                 float32 `protobuf:"fixed32,9,opt,name=balance,proto3" json:"balance,omitempty"`
	Status                  string  `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	Device                  string  `protobuf:"bytes,11,opt,name=device,proto3" json:"device,omitempty"`
	MerId                   string  `protobuf:"bytes,12,opt,name=merId,proto3" json:"merId,omitempty"`
	MerKey                  string  `protobuf:"bytes,13,opt,name=merKey,proto3" json:"merKey,omitempty"`
	PayUrl                  string  `protobuf:"bytes,14,opt,name=payUrl,proto3" json:"payUrl,omitempty"`
	PayQueryUrl             string  `protobuf:"bytes,15,opt,name=payQueryUrl,proto3" json:"payQueryUrl,omitempty"`
	PayQueryBalanceUrl      string  `protobuf:"bytes,16,opt,name=payQueryBalanceUrl,proto3" json:"payQueryBalanceUrl,omitempty"`
	ProxyPayUrl             string  `protobuf:"bytes,17,opt,name=proxyPayUrl,proto3" json:"proxyPayUrl,omitempty"`
	ProxyPayQueryUrl        string  `protobuf:"bytes,18,opt,name=proxyPayQueryUrl,proto3" json:"proxyPayQueryUrl,omitempty"`
	ProxyPayQueryBalanceUrl string  `protobuf:"bytes,19,opt,name=proxyPayQueryBalanceUrl,proto3" json:"proxyPayQueryBalanceUrl,omitempty"`
	WhiteList               string  `protobuf:"bytes,20,opt,name=whiteList,proto3" json:"whiteList,omitempty"`
	//    []PayTypeMap  payTypeMapList=20;
	PayTypeMap           string   `protobuf:"bytes,21,opt,name=payTypeMap,proto3" json:"payTypeMap,omitempty"`
	ChannelPort          string   `protobuf:"bytes,22,opt,name=channelPort,proto3" json:"channelPort,omitempty"`
	WithdrawBalance      float32  `protobuf:"fixed32,23,opt,name=withdrawBalance,proto3" json:"withdrawBalance,omitempty"`
	ProxypayBalance      float32  `protobuf:"fixed32,24,opt,name=proxypayBalance,proto3" json:"proxypayBalance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Channel) Reset()         { *m = Channel{} }
func (m *Channel) String() string { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()    {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac91597664078dc8, []int{0}
}

func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (m *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(m, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Channel) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Channel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Channel) GetIsProxy() string {
	if m != nil {
		return m.IsProxy
	}
	return ""
}

func (m *Channel) GetIsNzPre() string {
	if m != nil {
		return m.IsNzPre
	}
	return ""
}

func (m *Channel) GetApiUrl() string {
	if m != nil {
		return m.ApiUrl
	}
	return ""
}

func (m *Channel) GetCurrencyCode() string {
	if m != nil {
		return m.CurrencyCode
	}
	return ""
}

func (m *Channel) GetChannelWithdrawCharge() float32 {
	if m != nil {
		return m.ChannelWithdrawCharge
	}
	return 0
}

func (m *Channel) GetBalance() float32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Channel) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Channel) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *Channel) GetMerId() string {
	if m != nil {
		return m.MerId
	}
	return ""
}

func (m *Channel) GetMerKey() string {
	if m != nil {
		return m.MerKey
	}
	return ""
}

func (m *Channel) GetPayUrl() string {
	if m != nil {
		return m.PayUrl
	}
	return ""
}

func (m *Channel) GetPayQueryUrl() string {
	if m != nil {
		return m.PayQueryUrl
	}
	return ""
}

func (m *Channel) GetPayQueryBalanceUrl() string {
	if m != nil {
		return m.PayQueryBalanceUrl
	}
	return ""
}

func (m *Channel) GetProxyPayUrl() string {
	if m != nil {
		return m.ProxyPayUrl
	}
	return ""
}

func (m *Channel) GetProxyPayQueryUrl() string {
	if m != nil {
		return m.ProxyPayQueryUrl
	}
	return ""
}

func (m *Channel) GetProxyPayQueryBalanceUrl() string {
	if m != nil {
		return m.ProxyPayQueryBalanceUrl
	}
	return ""
}

func (m *Channel) GetWhiteList() string {
	if m != nil {
		return m.WhiteList
	}
	return ""
}

func (m *Channel) GetPayTypeMap() string {
	if m != nil {
		return m.PayTypeMap
	}
	return ""
}

func (m *Channel) GetChannelPort() string {
	if m != nil {
		return m.ChannelPort
	}
	return ""
}

func (m *Channel) GetWithdrawBalance() float32 {
	if m != nil {
		return m.WithdrawBalance
	}
	return 0
}

func (m *Channel) GetProxypayBalance() float32 {
	if m != nil {
		return m.ProxypayBalance
	}
	return 0
}

type TxPayOrderRequest struct {
	OrderNo              string   `protobuf:"bytes,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	PayType              string   `protobuf:"bytes,2,opt,name=payType,proto3" json:"payType,omitempty"`
	TransactionAmount    string   `protobuf:"bytes,3,opt,name=transactionAmount,proto3" json:"transactionAmount,omitempty"`
	BankCode             string   `protobuf:"bytes,4,opt,name=bankCode,proto3" json:"bankCode,omitempty"`
	PageUrl              string   `protobuf:"bytes,5,opt,name=pageUrl,proto3" json:"pageUrl,omitempty"`
	OrderName            string   `protobuf:"bytes,6,opt,name=orderName,proto3" json:"orderName,omitempty"`
	MerchantId           string   `protobuf:"bytes,7,opt,name=merchantId,proto3" json:"merchantId,omitempty"`
	Currency             string   `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	SourceIp             string   `protobuf:"bytes,9,opt,name=sourceIp,proto3" json:"sourceIp,omitempty"`
	UserId               string   `protobuf:"bytes,10,opt,name=userId,proto3" json:"userId,omitempty"`
	JumpType             string   `protobuf:"bytes,11,opt,name=jumpType,proto3" json:"jumpType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxPayOrderRequest) Reset()         { *m = TxPayOrderRequest{} }
func (m *TxPayOrderRequest) String() string { return proto.CompactTextString(m) }
func (*TxPayOrderRequest) ProtoMessage()    {}
func (*TxPayOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac91597664078dc8, []int{1}
}

func (m *TxPayOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxPayOrderRequest.Unmarshal(m, b)
}
func (m *TxPayOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxPayOrderRequest.Marshal(b, m, deterministic)
}
func (m *TxPayOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxPayOrderRequest.Merge(m, src)
}
func (m *TxPayOrderRequest) XXX_Size() int {
	return xxx_messageInfo_TxPayOrderRequest.Size(m)
}
func (m *TxPayOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxPayOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxPayOrderRequest proto.InternalMessageInfo

func (m *TxPayOrderRequest) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *TxPayOrderRequest) GetPayType() string {
	if m != nil {
		return m.PayType
	}
	return ""
}

func (m *TxPayOrderRequest) GetTransactionAmount() string {
	if m != nil {
		return m.TransactionAmount
	}
	return ""
}

func (m *TxPayOrderRequest) GetBankCode() string {
	if m != nil {
		return m.BankCode
	}
	return ""
}

func (m *TxPayOrderRequest) GetPageUrl() string {
	if m != nil {
		return m.PageUrl
	}
	return ""
}

func (m *TxPayOrderRequest) GetOrderName() string {
	if m != nil {
		return m.OrderName
	}
	return ""
}

func (m *TxPayOrderRequest) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *TxPayOrderRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *TxPayOrderRequest) GetSourceIp() string {
	if m != nil {
		return m.SourceIp
	}
	return ""
}

func (m *TxPayOrderRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TxPayOrderRequest) GetJumpType() string {
	if m != nil {
		return m.JumpType
	}
	return ""
}

type TxPayOrderResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxPayOrderResponse) Reset()         { *m = TxPayOrderResponse{} }
func (m *TxPayOrderResponse) String() string { return proto.CompactTextString(m) }
func (*TxPayOrderResponse) ProtoMessage()    {}
func (*TxPayOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac91597664078dc8, []int{2}
}

func (m *TxPayOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxPayOrderResponse.Unmarshal(m, b)
}
func (m *TxPayOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxPayOrderResponse.Marshal(b, m, deterministic)
}
func (m *TxPayOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxPayOrderResponse.Merge(m, src)
}
func (m *TxPayOrderResponse) XXX_Size() int {
	return xxx_messageInfo_TxPayOrderResponse.Size(m)
}
func (m *TxPayOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxPayOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxPayOrderResponse proto.InternalMessageInfo

func (m *TxPayOrderResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *TxPayOrderResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type TxPayQueryOrderRequest struct {
	OrderNo              string   `protobuf:"bytes,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	ChannelOrderNo       string   `protobuf:"bytes,2,opt,name=channelOrderNo,proto3" json:"channelOrderNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxPayQueryOrderRequest) Reset()         { *m = TxPayQueryOrderRequest{} }
func (m *TxPayQueryOrderRequest) String() string { return proto.CompactTextString(m) }
func (*TxPayQueryOrderRequest) ProtoMessage()    {}
func (*TxPayQueryOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac91597664078dc8, []int{3}
}

func (m *TxPayQueryOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxPayQueryOrderRequest.Unmarshal(m, b)
}
func (m *TxPayQueryOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxPayQueryOrderRequest.Marshal(b, m, deterministic)
}
func (m *TxPayQueryOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxPayQueryOrderRequest.Merge(m, src)
}
func (m *TxPayQueryOrderRequest) XXX_Size() int {
	return xxx_messageInfo_TxPayQueryOrderRequest.Size(m)
}
func (m *TxPayQueryOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxPayQueryOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxPayQueryOrderRequest proto.InternalMessageInfo

func (m *TxPayQueryOrderRequest) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *TxPayQueryOrderRequest) GetChannelOrderNo() string {
	if m != nil {
		return m.ChannelOrderNo
	}
	return ""
}

type TxPayQueryOrderResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxPayQueryOrderResponse) Reset()         { *m = TxPayQueryOrderResponse{} }
func (m *TxPayQueryOrderResponse) String() string { return proto.CompactTextString(m) }
func (*TxPayQueryOrderResponse) ProtoMessage()    {}
func (*TxPayQueryOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac91597664078dc8, []int{4}
}

func (m *TxPayQueryOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxPayQueryOrderResponse.Unmarshal(m, b)
}
func (m *TxPayQueryOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxPayQueryOrderResponse.Marshal(b, m, deterministic)
}
func (m *TxPayQueryOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxPayQueryOrderResponse.Merge(m, src)
}
func (m *TxPayQueryOrderResponse) XXX_Size() int {
	return xxx_messageInfo_TxPayQueryOrderResponse.Size(m)
}
func (m *TxPayQueryOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxPayQueryOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxPayQueryOrderResponse proto.InternalMessageInfo

func (m *TxPayQueryOrderResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *TxPayQueryOrderResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type TxPayQueryBalanceRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxPayQueryBalanceRequest) Reset()         { *m = TxPayQueryBalanceRequest{} }
func (m *TxPayQueryBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*TxPayQueryBalanceRequest) ProtoMessage()    {}
func (*TxPayQueryBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac91597664078dc8, []int{5}
}

func (m *TxPayQueryBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxPayQueryBalanceRequest.Unmarshal(m, b)
}
func (m *TxPayQueryBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxPayQueryBalanceRequest.Marshal(b, m, deterministic)
}
func (m *TxPayQueryBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxPayQueryBalanceRequest.Merge(m, src)
}
func (m *TxPayQueryBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_TxPayQueryBalanceRequest.Size(m)
}
func (m *TxPayQueryBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxPayQueryBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxPayQueryBalanceRequest proto.InternalMessageInfo

type TxPayQueryInternalBalanceResponse struct {
	ChannelNametring     string   `protobuf:"bytes,1,opt,name=channelNametring,proto3" json:"channelNametring,omitempty"`
	ChannelCodingtring   string   `protobuf:"bytes,2,opt,name=channelCodingtring,proto3" json:"channelCodingtring,omitempty"`
	WithdrawBalance      string   `protobuf:"bytes,3,opt,name=withdrawBalance,proto3" json:"withdrawBalance,omitempty"`
	ProxyPayBalance      string   `protobuf:"bytes,4,opt,name=proxyPayBalance,proto3" json:"proxyPayBalance,omitempty"`
	UpdateTimetring      string   `protobuf:"bytes,5,opt,name=updateTimetring,proto3" json:"updateTimetring,omitempty"`
	ErrorCodetring       string   `protobuf:"bytes,6,opt,name=errorCodetring,proto3" json:"errorCodetring,omitempty"`
	ErrorMsgtring        string   `protobuf:"bytes,7,opt,name=errorMsgtring,proto3" json:"errorMsgtring,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxPayQueryInternalBalanceResponse) Reset()         { *m = TxPayQueryInternalBalanceResponse{} }
func (m *TxPayQueryInternalBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*TxPayQueryInternalBalanceResponse) ProtoMessage()    {}
func (*TxPayQueryInternalBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac91597664078dc8, []int{6}
}

func (m *TxPayQueryInternalBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxPayQueryInternalBalanceResponse.Unmarshal(m, b)
}
func (m *TxPayQueryInternalBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxPayQueryInternalBalanceResponse.Marshal(b, m, deterministic)
}
func (m *TxPayQueryInternalBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxPayQueryInternalBalanceResponse.Merge(m, src)
}
func (m *TxPayQueryInternalBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_TxPayQueryInternalBalanceResponse.Size(m)
}
func (m *TxPayQueryInternalBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxPayQueryInternalBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxPayQueryInternalBalanceResponse proto.InternalMessageInfo

func (m *TxPayQueryInternalBalanceResponse) GetChannelNametring() string {
	if m != nil {
		return m.ChannelNametring
	}
	return ""
}

func (m *TxPayQueryInternalBalanceResponse) GetChannelCodingtring() string {
	if m != nil {
		return m.ChannelCodingtring
	}
	return ""
}

func (m *TxPayQueryInternalBalanceResponse) GetWithdrawBalance() string {
	if m != nil {
		return m.WithdrawBalance
	}
	return ""
}

func (m *TxPayQueryInternalBalanceResponse) GetProxyPayBalance() string {
	if m != nil {
		return m.ProxyPayBalance
	}
	return ""
}

func (m *TxPayQueryInternalBalanceResponse) GetUpdateTimetring() string {
	if m != nil {
		return m.UpdateTimetring
	}
	return ""
}

func (m *TxPayQueryInternalBalanceResponse) GetErrorCodetring() string {
	if m != nil {
		return m.ErrorCodetring
	}
	return ""
}

func (m *TxPayQueryInternalBalanceResponse) GetErrorMsgtring() string {
	if m != nil {
		return m.ErrorMsgtring
	}
	return ""
}

type TxProxyPayOrderRequest struct {
	OrderNo              string   `protobuf:"bytes,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	TransactionType      string   `protobuf:"bytes,2,opt,name=transactionType,proto3" json:"transactionType,omitempty"`
	TransactionAmount    string   `protobuf:"bytes,3,opt,name=transactionAmount,proto3" json:"transactionAmount,omitempty"`
	ReceiptAccountNumber string   `protobuf:"bytes,4,opt,name=receiptAccountNumber,proto3" json:"receiptAccountNumber,omitempty"`
	ReceiptAccountName   string   `protobuf:"bytes,5,opt,name=receiptAccountName,proto3" json:"receiptAccountName,omitempty"`
	ReceiptCardProvince  string   `protobuf:"bytes,6,opt,name=receiptCardProvince,proto3" json:"receiptCardProvince,omitempty"`
	ReceiptCardCity      string   `protobuf:"bytes,7,opt,name=receiptCardCity,proto3" json:"receiptCardCity,omitempty"`
	ReceiptCardArea      string   `protobuf:"bytes,8,opt,name=receiptCardArea,proto3" json:"receiptCardArea,omitempty"`
	ReceiptCardBranch    string   `protobuf:"bytes,9,opt,name=receiptCardBranch,proto3" json:"receiptCardBranch,omitempty"`
	ReceiptCardBankCode  string   `protobuf:"bytes,10,opt,name=receiptCardBankCode,proto3" json:"receiptCardBankCode,omitempty"`
	ReceiptCardBankName  string   `protobuf:"bytes,11,opt,name=receiptCardBankName,proto3" json:"receiptCardBankName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxProxyPayOrderRequest) Reset()         { *m = TxProxyPayOrderRequest{} }
func (m *TxProxyPayOrderRequest) String() string { return proto.CompactTextString(m) }
func (*TxProxyPayOrderRequest) ProtoMessage()    {}
func (*TxProxyPayOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac91597664078dc8, []int{7}
}

func (m *TxProxyPayOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxProxyPayOrderRequest.Unmarshal(m, b)
}
func (m *TxProxyPayOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxProxyPayOrderRequest.Marshal(b, m, deterministic)
}
func (m *TxProxyPayOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxProxyPayOrderRequest.Merge(m, src)
}
func (m *TxProxyPayOrderRequest) XXX_Size() int {
	return xxx_messageInfo_TxProxyPayOrderRequest.Size(m)
}
func (m *TxProxyPayOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxProxyPayOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxProxyPayOrderRequest proto.InternalMessageInfo

func (m *TxProxyPayOrderRequest) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *TxProxyPayOrderRequest) GetTransactionType() string {
	if m != nil {
		return m.TransactionType
	}
	return ""
}

func (m *TxProxyPayOrderRequest) GetTransactionAmount() string {
	if m != nil {
		return m.TransactionAmount
	}
	return ""
}

func (m *TxProxyPayOrderRequest) GetReceiptAccountNumber() string {
	if m != nil {
		return m.ReceiptAccountNumber
	}
	return ""
}

func (m *TxProxyPayOrderRequest) GetReceiptAccountName() string {
	if m != nil {
		return m.ReceiptAccountName
	}
	return ""
}

func (m *TxProxyPayOrderRequest) GetReceiptCardProvince() string {
	if m != nil {
		return m.ReceiptCardProvince
	}
	return ""
}

func (m *TxProxyPayOrderRequest) GetReceiptCardCity() string {
	if m != nil {
		return m.ReceiptCardCity
	}
	return ""
}

func (m *TxProxyPayOrderRequest) GetReceiptCardArea() string {
	if m != nil {
		return m.ReceiptCardArea
	}
	return ""
}

func (m *TxProxyPayOrderRequest) GetReceiptCardBranch() string {
	if m != nil {
		return m.ReceiptCardBranch
	}
	return ""
}

func (m *TxProxyPayOrderRequest) GetReceiptCardBankCode() string {
	if m != nil {
		return m.ReceiptCardBankCode
	}
	return ""
}

func (m *TxProxyPayOrderRequest) GetReceiptCardBankName() string {
	if m != nil {
		return m.ReceiptCardBankName
	}
	return ""
}

type TxProxyPayOrderResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxProxyPayOrderResponse) Reset()         { *m = TxProxyPayOrderResponse{} }
func (m *TxProxyPayOrderResponse) String() string { return proto.CompactTextString(m) }
func (*TxProxyPayOrderResponse) ProtoMessage()    {}
func (*TxProxyPayOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac91597664078dc8, []int{8}
}

func (m *TxProxyPayOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxProxyPayOrderResponse.Unmarshal(m, b)
}
func (m *TxProxyPayOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxProxyPayOrderResponse.Marshal(b, m, deterministic)
}
func (m *TxProxyPayOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxProxyPayOrderResponse.Merge(m, src)
}
func (m *TxProxyPayOrderResponse) XXX_Size() int {
	return xxx_messageInfo_TxProxyPayOrderResponse.Size(m)
}
func (m *TxProxyPayOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxProxyPayOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxProxyPayOrderResponse proto.InternalMessageInfo

func (m *TxProxyPayOrderResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *TxProxyPayOrderResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type TxProxyPayQueryRequest struct {
	OrderNo              string   `protobuf:"bytes,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	ChannelOrderNo       string   `protobuf:"bytes,2,opt,name=channelOrderNo,proto3" json:"channelOrderNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxProxyPayQueryRequest) Reset()         { *m = TxProxyPayQueryRequest{} }
func (m *TxProxyPayQueryRequest) String() string { return proto.CompactTextString(m) }
func (*TxProxyPayQueryRequest) ProtoMessage()    {}
func (*TxProxyPayQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac91597664078dc8, []int{9}
}

func (m *TxProxyPayQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxProxyPayQueryRequest.Unmarshal(m, b)
}
func (m *TxProxyPayQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxProxyPayQueryRequest.Marshal(b, m, deterministic)
}
func (m *TxProxyPayQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxProxyPayQueryRequest.Merge(m, src)
}
func (m *TxProxyPayQueryRequest) XXX_Size() int {
	return xxx_messageInfo_TxProxyPayQueryRequest.Size(m)
}
func (m *TxProxyPayQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxProxyPayQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxProxyPayQueryRequest proto.InternalMessageInfo

func (m *TxProxyPayQueryRequest) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *TxProxyPayQueryRequest) GetChannelOrderNo() string {
	if m != nil {
		return m.ChannelOrderNo
	}
	return ""
}

type TxProxyPayQueryResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxProxyPayQueryResponse) Reset()         { *m = TxProxyPayQueryResponse{} }
func (m *TxProxyPayQueryResponse) String() string { return proto.CompactTextString(m) }
func (*TxProxyPayQueryResponse) ProtoMessage()    {}
func (*TxProxyPayQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac91597664078dc8, []int{10}
}

func (m *TxProxyPayQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxProxyPayQueryResponse.Unmarshal(m, b)
}
func (m *TxProxyPayQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxProxyPayQueryResponse.Marshal(b, m, deterministic)
}
func (m *TxProxyPayQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxProxyPayQueryResponse.Merge(m, src)
}
func (m *TxProxyPayQueryResponse) XXX_Size() int {
	return xxx_messageInfo_TxProxyPayQueryResponse.Size(m)
}
func (m *TxProxyPayQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxProxyPayQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxProxyPayQueryResponse proto.InternalMessageInfo

func (m *TxProxyPayQueryResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *TxProxyPayQueryResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type TxProxyPayQueryInternalBalanceRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxProxyPayQueryInternalBalanceRequest) Reset()         { *m = TxProxyPayQueryInternalBalanceRequest{} }
func (m *TxProxyPayQueryInternalBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*TxProxyPayQueryInternalBalanceRequest) ProtoMessage()    {}
func (*TxProxyPayQueryInternalBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac91597664078dc8, []int{11}
}

func (m *TxProxyPayQueryInternalBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxProxyPayQueryInternalBalanceRequest.Unmarshal(m, b)
}
func (m *TxProxyPayQueryInternalBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxProxyPayQueryInternalBalanceRequest.Marshal(b, m, deterministic)
}
func (m *TxProxyPayQueryInternalBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxProxyPayQueryInternalBalanceRequest.Merge(m, src)
}
func (m *TxProxyPayQueryInternalBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_TxProxyPayQueryInternalBalanceRequest.Size(m)
}
func (m *TxProxyPayQueryInternalBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxProxyPayQueryInternalBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxProxyPayQueryInternalBalanceRequest proto.InternalMessageInfo

type TxProxyPayQueryInternalBalanceResponse struct {
	ChannelNametring     string   `protobuf:"bytes,1,opt,name=channelNametring,proto3" json:"channelNametring,omitempty"`
	ChannelCodingtring   string   `protobuf:"bytes,2,opt,name=channelCodingtring,proto3" json:"channelCodingtring,omitempty"`
	WithdrawBalance      string   `protobuf:"bytes,3,opt,name=withdrawBalance,proto3" json:"withdrawBalance,omitempty"`
	ProxyPayBalance      string   `protobuf:"bytes,4,opt,name=proxyPayBalance,proto3" json:"proxyPayBalance,omitempty"`
	UpdateTimetring      string   `protobuf:"bytes,5,opt,name=updateTimetring,proto3" json:"updateTimetring,omitempty"`
	ErrorCodetring       string   `protobuf:"bytes,6,opt,name=errorCodetring,proto3" json:"errorCodetring,omitempty"`
	ErrorMsgtring        string   `protobuf:"bytes,7,opt,name=errorMsgtring,proto3" json:"errorMsgtring,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxProxyPayQueryInternalBalanceResponse) Reset() {
	*m = TxProxyPayQueryInternalBalanceResponse{}
}
func (m *TxProxyPayQueryInternalBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*TxProxyPayQueryInternalBalanceResponse) ProtoMessage()    {}
func (*TxProxyPayQueryInternalBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac91597664078dc8, []int{12}
}

func (m *TxProxyPayQueryInternalBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxProxyPayQueryInternalBalanceResponse.Unmarshal(m, b)
}
func (m *TxProxyPayQueryInternalBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxProxyPayQueryInternalBalanceResponse.Marshal(b, m, deterministic)
}
func (m *TxProxyPayQueryInternalBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxProxyPayQueryInternalBalanceResponse.Merge(m, src)
}
func (m *TxProxyPayQueryInternalBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_TxProxyPayQueryInternalBalanceResponse.Size(m)
}
func (m *TxProxyPayQueryInternalBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxProxyPayQueryInternalBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxProxyPayQueryInternalBalanceResponse proto.InternalMessageInfo

func (m *TxProxyPayQueryInternalBalanceResponse) GetChannelNametring() string {
	if m != nil {
		return m.ChannelNametring
	}
	return ""
}

func (m *TxProxyPayQueryInternalBalanceResponse) GetChannelCodingtring() string {
	if m != nil {
		return m.ChannelCodingtring
	}
	return ""
}

func (m *TxProxyPayQueryInternalBalanceResponse) GetWithdrawBalance() string {
	if m != nil {
		return m.WithdrawBalance
	}
	return ""
}

func (m *TxProxyPayQueryInternalBalanceResponse) GetProxyPayBalance() string {
	if m != nil {
		return m.ProxyPayBalance
	}
	return ""
}

func (m *TxProxyPayQueryInternalBalanceResponse) GetUpdateTimetring() string {
	if m != nil {
		return m.UpdateTimetring
	}
	return ""
}

func (m *TxProxyPayQueryInternalBalanceResponse) GetErrorCodetring() string {
	if m != nil {
		return m.ErrorCodetring
	}
	return ""
}

func (m *TxProxyPayQueryInternalBalanceResponse) GetErrorMsgtring() string {
	if m != nil {
		return m.ErrorMsgtring
	}
	return ""
}

func init() {
	proto.RegisterType((*Channel)(nil), "txpay.channel")
	proto.RegisterType((*TxPayOrderRequest)(nil), "txpay.TxPayOrderRequest")
	proto.RegisterType((*TxPayOrderResponse)(nil), "txpay.TxPayOrderResponse")
	proto.RegisterType((*TxPayQueryOrderRequest)(nil), "txpay.TxPayQueryOrderRequest")
	proto.RegisterType((*TxPayQueryOrderResponse)(nil), "txpay.TxPayQueryOrderResponse")
	proto.RegisterType((*TxPayQueryBalanceRequest)(nil), "txpay.TxPayQueryBalanceRequest")
	proto.RegisterType((*TxPayQueryInternalBalanceResponse)(nil), "txpay.TxPayQueryInternalBalanceResponse")
	proto.RegisterType((*TxProxyPayOrderRequest)(nil), "txpay.TxProxyPayOrderRequest")
	proto.RegisterType((*TxProxyPayOrderResponse)(nil), "txpay.TxProxyPayOrderResponse")
	proto.RegisterType((*TxProxyPayQueryRequest)(nil), "txpay.TxProxyPayQueryRequest")
	proto.RegisterType((*TxProxyPayQueryResponse)(nil), "txpay.TxProxyPayQueryResponse")
	proto.RegisterType((*TxProxyPayQueryInternalBalanceRequest)(nil), "txpay.TxProxyPayQueryInternalBalanceRequest")
	proto.RegisterType((*TxProxyPayQueryInternalBalanceResponse)(nil), "txpay.TxProxyPayQueryInternalBalanceResponse")
}

func init() { proto.RegisterFile("txpay.proto", fileDescriptor_ac91597664078dc8) }

var fileDescriptor_ac91597664078dc8 = []byte{
	// 984 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0xcf, 0x6f, 0xe3, 0x44,
	0x14, 0x56, 0xd2, 0xa6, 0xdd, 0xbc, 0xee, 0xf6, 0xc7, 0x6c, 0xb7, 0x1d, 0x22, 0x58, 0x4a, 0x04,
	0x4b, 0xb4, 0x5a, 0x2a, 0xb4, 0x70, 0x40, 0x5c, 0x50, 0x9b, 0x53, 0x05, 0xdb, 0x0d, 0x51, 0x57,
	0x48, 0x1c, 0x90, 0xa6, 0xf6, 0x28, 0x31, 0x34, 0xb6, 0x19, 0x8f, 0xb7, 0x35, 0x77, 0xf8, 0x2b,
	0xf8, 0x8f, 0xb8, 0x70, 0xe1, 0xff, 0x41, 0xef, 0xbd, 0x71, 0x3c, 0xb1, 0x5d, 0xd1, 0x22, 0x8e,
	0xdc, 0xf2, 0xbe, 0xef, 0xcd, 0xcc, 0xe7, 0x37, 0xef, 0x7b, 0x76, 0x60, 0xcb, 0xde, 0xa4, 0xaa,
	0x38, 0x4e, 0x4d, 0x62, 0x13, 0xd1, 0xa3, 0x60, 0xf8, 0xeb, 0x06, 0x6c, 0x06, 0x73, 0x15, 0xc7,
	0xfa, 0x4a, 0x6c, 0x43, 0x37, 0x0a, 0x65, 0xe7, 0xa8, 0x33, 0x5a, 0x9b, 0x76, 0xa3, 0x50, 0x08,
	0x58, 0x0f, 0x92, 0x50, 0xcb, 0xee, 0x51, 0x67, 0xd4, 0x9f, 0xd2, 0x6f, 0xc4, 0x62, 0xb5, 0xd0,
	0x72, 0x8d, 0x31, 0xfc, 0x2d, 0x24, 0x6c, 0x46, 0xd9, 0xc4, 0x24, 0x37, 0x85, 0x5c, 0x27, 0xb8,
	0x0c, 0x99, 0x39, 0xff, 0x65, 0x62, 0xb4, 0xec, 0x95, 0x0c, 0x85, 0xe2, 0x00, 0x36, 0x54, 0x1a,
	0xbd, 0x31, 0x57, 0x72, 0x83, 0x08, 0x17, 0x89, 0x21, 0x3c, 0x0c, 0x72, 0x63, 0x74, 0x1c, 0x14,
	0x63, 0x3c, 0x7b, 0x93, 0xd8, 0x15, 0x4c, 0x7c, 0x0e, 0x4f, 0x9c, 0xe4, 0xef, 0x22, 0x3b, 0x0f,
	0x8d, 0xba, 0x1e, 0xcf, 0x95, 0x99, 0x69, 0xf9, 0xe0, 0xa8, 0x33, 0xea, 0x4e, 0xdb, 0x49, 0xd4,
	0x72, 0xa9, 0xae, 0x54, 0x1c, 0x68, 0xd9, 0xa7, 0xbc, 0x32, 0x44, 0x2d, 0x99, 0x55, 0x36, 0xcf,
	0x24, 0xb0, 0x16, 0x8e, 0x10, 0x0f, 0xf5, 0xdb, 0x28, 0xd0, 0x72, 0x8b, 0x71, 0x8e, 0xc4, 0x3e,
	0xf4, 0x16, 0xda, 0x9c, 0x85, 0xf2, 0x21, 0xc1, 0x1c, 0x60, 0xf6, 0x42, 0x9b, 0xaf, 0x75, 0x21,
	0x1f, 0x71, 0x36, 0x47, 0x88, 0xa7, 0xaa, 0xc0, 0x27, 0xdd, 0x66, 0x9c, 0x23, 0x71, 0x04, 0x5b,
	0xa9, 0x2a, 0xbe, 0xcd, 0xb5, 0x21, 0x72, 0x87, 0x48, 0x1f, 0x12, 0xc7, 0x20, 0xca, 0xf0, 0x94,
	0xa5, 0x62, 0xe2, 0x2e, 0x25, 0xb6, 0x30, 0xb4, 0x23, 0x96, 0x7d, 0xc2, 0xc7, 0xed, 0xb9, 0x1d,
	0x2b, 0x48, 0x3c, 0x87, 0xdd, 0x32, 0x5c, 0x1e, 0x2c, 0x28, 0xad, 0x81, 0x8b, 0x2f, 0xe0, 0x70,
	0x05, 0xf3, 0x24, 0x3c, 0xa6, 0x25, 0xb7, 0xd1, 0xe2, 0x5d, 0xe8, 0x5f, 0xcf, 0x23, 0xab, 0xbf,
	0x89, 0x32, 0x2b, 0xf7, 0x29, 0xb7, 0x02, 0xc4, 0x53, 0x80, 0x54, 0x15, 0x17, 0x45, 0xaa, 0x5f,
	0xa9, 0x54, 0x3e, 0x21, 0xda, 0x43, 0xf0, 0x29, 0xdc, 0x05, 0x4e, 0x12, 0x63, 0xe5, 0x01, 0x3f,
	0x85, 0x07, 0x89, 0x11, 0xec, 0x5c, 0xbb, 0xbb, 0x75, 0xa7, 0xca, 0x43, 0xba, 0xd1, 0x3a, 0x8c,
	0x99, 0x24, 0x32, 0x55, 0xa5, 0x3e, 0x29, 0x39, 0xb3, 0x06, 0x0f, 0xff, 0xea, 0xc2, 0xde, 0xc5,
	0xcd, 0x44, 0x15, 0xaf, 0x4d, 0xa8, 0xcd, 0x54, 0xff, 0x9c, 0xeb, 0xcc, 0x62, 0xcf, 0x24, 0x18,
	0x9f, 0x27, 0x64, 0x8b, 0xfe, 0xb4, 0x0c, 0x91, 0x71, 0x9a, 0x9d, 0x3d, 0xca, 0x50, 0xbc, 0x80,
	0x3d, 0x6b, 0x54, 0x9c, 0xa9, 0xc0, 0x46, 0x49, 0x7c, 0xb2, 0x48, 0xf2, 0xd8, 0x3a, 0xbb, 0x34,
	0x09, 0x31, 0x80, 0x07, 0x97, 0x2a, 0xfe, 0x89, 0x7a, 0x9d, 0xcd, 0xb3, 0x8c, 0xf9, 0x8c, 0x19,
	0x55, 0xbc, 0x57, 0x9e, 0x31, 0x2b, 0x2b, 0xcc, 0x42, 0xd0, 0x8a, 0x6c, 0xa0, 0x0a, 0xc0, 0x0a,
	0x2f, 0xb4, 0xc1, 0x8a, 0xd9, 0xb3, 0xd0, 0x39, 0xc8, 0x43, 0xf0, 0xcc, 0xd2, 0x4f, 0x64, 0x99,
	0xfe, 0x74, 0x19, 0x23, 0x97, 0x25, 0xb9, 0x09, 0xf4, 0x59, 0x4a, 0x36, 0xe9, 0x4f, 0x97, 0x31,
	0x76, 0x72, 0x9e, 0x51, 0xe3, 0x3b, 0x9f, 0x70, 0x84, 0x6b, 0x7e, 0xcc, 0x17, 0x29, 0x15, 0x83,
	0x9d, 0xb2, 0x8c, 0x87, 0x5f, 0x82, 0xf0, 0xcb, 0x9a, 0xa5, 0x49, 0x9c, 0xe9, 0xe5, 0x64, 0xe9,
	0x78, 0x93, 0x65, 0x17, 0xd6, 0x16, 0xd9, 0xcc, 0x55, 0x13, 0x7f, 0x0e, 0xbf, 0x87, 0x03, 0x5a,
	0x4b, 0xfd, 0x75, 0xc7, 0x7b, 0x79, 0x06, 0xdb, 0xae, 0x55, 0x5e, 0xbb, 0x04, 0xde, 0xb0, 0x86,
	0x0e, 0xbf, 0x82, 0xc3, 0xc6, 0xde, 0xf7, 0x12, 0x37, 0x00, 0x59, 0x6d, 0xe0, 0xba, 0xc8, 0xc9,
	0x1b, 0xfe, 0xd1, 0x85, 0x0f, 0x2a, 0xf2, 0x2c, 0xb6, 0xda, 0xc4, 0xea, 0x6a, 0x99, 0xe4, 0xce,
	0x79, 0x0e, 0xbb, 0x4e, 0x14, 0xde, 0x9a, 0x35, 0x51, 0x3c, 0x73, 0x67, 0x36, 0x70, 0x1c, 0x05,
	0x0e, 0x1b, 0x27, 0x61, 0x14, 0xcf, 0x38, 0x9b, 0xe5, 0xb4, 0x30, 0x6d, 0x16, 0xe1, 0x16, 0xbc,
	0xd5, 0x22, 0x93, 0xca, 0x22, 0xdc, 0x87, 0x75, 0x18, 0x33, 0xf3, 0x34, 0x54, 0x56, 0x5f, 0x44,
	0xa5, 0x5c, 0x6e, 0xcb, 0x3a, 0x8c, 0x97, 0xa0, 0x8d, 0x49, 0x0c, 0x76, 0x31, 0x27, 0x72, 0x8f,
	0xd6, 0x50, 0xf1, 0x21, 0x3c, 0x22, 0xe4, 0x55, 0xe6, 0x1e, 0x88, 0x7b, 0x75, 0x15, 0x1c, 0xfe,
	0xb6, 0x4e, 0x7d, 0xe0, 0xd4, 0xdc, 0xb1, 0x0f, 0x46, 0xb0, 0xe3, 0x99, 0xcd, 0xf3, 0x69, 0x1d,
	0xbe, 0xa7, 0x5f, 0x5f, 0xc2, 0xbe, 0xd1, 0x81, 0x8e, 0x52, 0x7b, 0x12, 0x04, 0x88, 0x9c, 0xe7,
	0x8b, 0x4b, 0x6d, 0x5c, 0xcd, 0x5a, 0x39, 0xbc, 0xbc, 0x1a, 0x8e, 0xb6, 0xe5, 0xda, 0xb5, 0x30,
	0xe2, 0x53, 0x78, 0xec, 0xd0, 0xb1, 0x32, 0xe1, 0xc4, 0x24, 0x6f, 0x23, 0xbc, 0x16, 0xae, 0x61,
	0x1b, 0x85, 0x4f, 0xeb, 0xc1, 0xe3, 0xc8, 0x16, 0xae, 0x94, 0x75, 0xb8, 0x96, 0x79, 0x62, 0xb4,
	0x72, 0x23, 0xa0, 0x0e, 0x63, 0x5d, 0x3c, 0xe8, 0xd4, 0xa8, 0x38, 0x98, 0xbb, 0x91, 0xd0, 0x24,
	0x6a, 0x9a, 0x4f, 0xcb, 0x91, 0x06, 0x0d, 0xcd, 0x25, 0xd5, 0xb2, 0x82, 0xca, 0xb2, 0xd5, 0xba,
	0x02, 0x29, 0xe7, 0xd9, 0xd5, 0x3e, 0xf8, 0x17, 0x03, 0xc5, 0x7f, 0x6b, 0xfd, 0xd7, 0x03, 0x65,
	0x75, 0xef, 0x7b, 0x89, 0xfb, 0x18, 0x3e, 0xaa, 0x6d, 0xd0, 0x18, 0x1c, 0x3c, 0x5d, 0xfe, 0xec,
	0xc2, 0xb3, 0x7f, 0xca, 0xfc, 0x7f, 0xc4, 0xdc, 0x67, 0xc4, 0xbc, 0xfc, 0x7d, 0x1d, 0x7a, 0x34,
	0xb0, 0xc5, 0x09, 0x40, 0xf5, 0xbe, 0x12, 0xf2, 0x98, 0x3f, 0x99, 0x1b, 0x5f, 0x06, 0x83, 0x77,
	0x5a, 0x18, 0x57, 0xf4, 0x09, 0xec, 0x54, 0x28, 0x5d, 0x8f, 0x78, 0xcf, 0xcf, 0x6e, 0xbc, 0xce,
	0x06, 0x4f, 0x6f, 0xa3, 0xdd, 0x8e, 0x3f, 0xb8, 0x6f, 0x13, 0xff, 0x5d, 0x23, 0xde, 0x6f, 0x2c,
	0x5a, 0xed, 0x93, 0xc1, 0xa8, 0x91, 0x70, 0x5b, 0x9b, 0xb0, 0x62, 0xdf, 0x58, 0xbe, 0xe2, 0x96,
	0xc1, 0xeb, 0x2b, 0x6e, 0xf5, 0xe3, 0x1b, 0xd8, 0xaf, 0x51, 0x8d, 0x42, 0xb4, 0xd8, 0xb0, 0x65,
	0xdb, 0x55, 0x27, 0xe5, 0x0d, 0x03, 0x97, 0xd5, 0x78, 0xd1, 0xbe, 0xb2, 0xdd, 0x42, 0x83, 0x4f,
	0xee, 0x98, 0xcd, 0xc7, 0x5e, 0x6e, 0xd0, 0x5f, 0xa6, 0xcf, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff,
	0xae, 0x4a, 0x72, 0xb6, 0x41, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TxPayClient is the client API for TxPay service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TxPayClient interface {
	TxPayOrder(ctx context.Context, in *TxPayOrderRequest, opts ...grpc.CallOption) (*TxPayOrderResponse, error)
	TxPayOrderQuery(ctx context.Context, in *TxPayQueryOrderRequest, opts ...grpc.CallOption) (*TxPayQueryOrderResponse, error)
	TxPayQueryBalance(ctx context.Context, in *TxPayQueryBalanceRequest, opts ...grpc.CallOption) (*TxPayQueryInternalBalanceResponse, error)
	TxProxyPayOrder(ctx context.Context, in *TxProxyPayOrderRequest, opts ...grpc.CallOption) (*TxProxyPayOrderResponse, error)
	TxProxyPayOrderQuery(ctx context.Context, in *TxProxyPayQueryRequest, opts ...grpc.CallOption) (*TxProxyPayQueryResponse, error)
	TxProxyPayQueryBalance(ctx context.Context, in *TxProxyPayQueryInternalBalanceRequest, opts ...grpc.CallOption) (*TxProxyPayQueryInternalBalanceResponse, error)
}

type txPayClient struct {
	cc *grpc.ClientConn
}

func NewTxPayClient(cc *grpc.ClientConn) TxPayClient {
	return &txPayClient{cc}
}

func (c *txPayClient) TxPayOrder(ctx context.Context, in *TxPayOrderRequest, opts ...grpc.CallOption) (*TxPayOrderResponse, error) {
	out := new(TxPayOrderResponse)
	err := c.cc.Invoke(ctx, "/txpay.TxPay/TxPayOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *txPayClient) TxPayOrderQuery(ctx context.Context, in *TxPayQueryOrderRequest, opts ...grpc.CallOption) (*TxPayQueryOrderResponse, error) {
	out := new(TxPayQueryOrderResponse)
	err := c.cc.Invoke(ctx, "/txpay.TxPay/TxPayOrderQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *txPayClient) TxPayQueryBalance(ctx context.Context, in *TxPayQueryBalanceRequest, opts ...grpc.CallOption) (*TxPayQueryInternalBalanceResponse, error) {
	out := new(TxPayQueryInternalBalanceResponse)
	err := c.cc.Invoke(ctx, "/txpay.TxPay/TxPayQueryBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *txPayClient) TxProxyPayOrder(ctx context.Context, in *TxProxyPayOrderRequest, opts ...grpc.CallOption) (*TxProxyPayOrderResponse, error) {
	out := new(TxProxyPayOrderResponse)
	err := c.cc.Invoke(ctx, "/txpay.TxPay/TxProxyPayOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *txPayClient) TxProxyPayOrderQuery(ctx context.Context, in *TxProxyPayQueryRequest, opts ...grpc.CallOption) (*TxProxyPayQueryResponse, error) {
	out := new(TxProxyPayQueryResponse)
	err := c.cc.Invoke(ctx, "/txpay.TxPay/TxProxyPayOrderQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *txPayClient) TxProxyPayQueryBalance(ctx context.Context, in *TxProxyPayQueryInternalBalanceRequest, opts ...grpc.CallOption) (*TxProxyPayQueryInternalBalanceResponse, error) {
	out := new(TxProxyPayQueryInternalBalanceResponse)
	err := c.cc.Invoke(ctx, "/txpay.TxPay/TxProxyPayQueryBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TxPayServer is the server API for TxPay service.
type TxPayServer interface {
	TxPayOrder(context.Context, *TxPayOrderRequest) (*TxPayOrderResponse, error)
	TxPayOrderQuery(context.Context, *TxPayQueryOrderRequest) (*TxPayQueryOrderResponse, error)
	TxPayQueryBalance(context.Context, *TxPayQueryBalanceRequest) (*TxPayQueryInternalBalanceResponse, error)
	TxProxyPayOrder(context.Context, *TxProxyPayOrderRequest) (*TxProxyPayOrderResponse, error)
	TxProxyPayOrderQuery(context.Context, *TxProxyPayQueryRequest) (*TxProxyPayQueryResponse, error)
	TxProxyPayQueryBalance(context.Context, *TxProxyPayQueryInternalBalanceRequest) (*TxProxyPayQueryInternalBalanceResponse, error)
}

// UnimplementedTxPayServer can be embedded to have forward compatible implementations.
type UnimplementedTxPayServer struct {
}

func (*UnimplementedTxPayServer) TxPayOrder(ctx context.Context, req *TxPayOrderRequest) (*TxPayOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TxPayOrder not implemented")
}
func (*UnimplementedTxPayServer) TxPayOrderQuery(ctx context.Context, req *TxPayQueryOrderRequest) (*TxPayQueryOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TxPayOrderQuery not implemented")
}
func (*UnimplementedTxPayServer) TxPayQueryBalance(ctx context.Context, req *TxPayQueryBalanceRequest) (*TxPayQueryInternalBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TxPayQueryBalance not implemented")
}
func (*UnimplementedTxPayServer) TxProxyPayOrder(ctx context.Context, req *TxProxyPayOrderRequest) (*TxProxyPayOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TxProxyPayOrder not implemented")
}
func (*UnimplementedTxPayServer) TxProxyPayOrderQuery(ctx context.Context, req *TxProxyPayQueryRequest) (*TxProxyPayQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TxProxyPayOrderQuery not implemented")
}
func (*UnimplementedTxPayServer) TxProxyPayQueryBalance(ctx context.Context, req *TxProxyPayQueryInternalBalanceRequest) (*TxProxyPayQueryInternalBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TxProxyPayQueryBalance not implemented")
}

func RegisterTxPayServer(s *grpc.Server, srv TxPayServer) {
	s.RegisterService(&_TxPay_serviceDesc, srv)
}

func _TxPay_TxPayOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxPayOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxPayServer).TxPayOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/txpay.TxPay/TxPayOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxPayServer).TxPayOrder(ctx, req.(*TxPayOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TxPay_TxPayOrderQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxPayQueryOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxPayServer).TxPayOrderQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/txpay.TxPay/TxPayOrderQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxPayServer).TxPayOrderQuery(ctx, req.(*TxPayQueryOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TxPay_TxPayQueryBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxPayQueryBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxPayServer).TxPayQueryBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/txpay.TxPay/TxPayQueryBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxPayServer).TxPayQueryBalance(ctx, req.(*TxPayQueryBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TxPay_TxProxyPayOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxProxyPayOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxPayServer).TxProxyPayOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/txpay.TxPay/TxProxyPayOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxPayServer).TxProxyPayOrder(ctx, req.(*TxProxyPayOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TxPay_TxProxyPayOrderQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxProxyPayQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxPayServer).TxProxyPayOrderQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/txpay.TxPay/TxProxyPayOrderQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxPayServer).TxProxyPayOrderQuery(ctx, req.(*TxProxyPayQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TxPay_TxProxyPayQueryBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxProxyPayQueryInternalBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxPayServer).TxProxyPayQueryBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/txpay.TxPay/TxProxyPayQueryBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxPayServer).TxProxyPayQueryBalance(ctx, req.(*TxProxyPayQueryInternalBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TxPay_serviceDesc = grpc.ServiceDesc{
	ServiceName: "txpay.TxPay",
	HandlerType: (*TxPayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TxPayOrder",
			Handler:    _TxPay_TxPayOrder_Handler,
		},
		{
			MethodName: "TxPayOrderQuery",
			Handler:    _TxPay_TxPayOrderQuery_Handler,
		},
		{
			MethodName: "TxPayQueryBalance",
			Handler:    _TxPay_TxPayQueryBalance_Handler,
		},
		{
			MethodName: "TxProxyPayOrder",
			Handler:    _TxPay_TxProxyPayOrder_Handler,
		},
		{
			MethodName: "TxProxyPayOrderQuery",
			Handler:    _TxPay_TxProxyPayOrderQuery_Handler,
		},
		{
			MethodName: "TxProxyPayQueryBalance",
			Handler:    _TxPay_TxProxyPayQueryBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "txpay.proto",
}
