// Code generated by goctl. DO NOT EDIT!
// Source: txpay.proto

package txpayclient

import (
	"context"

	"github.com/copo888/channel_app/txpay/rpc/txpay"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Bank                                   = txpay.Bank
	Channel                                = txpay.Channel
	TxPayOrderRequest                      = txpay.TxPayOrderRequest
	TxPayOrderResponse                     = txpay.TxPayOrderResponse
	TxPayQueryBalanceRequest               = txpay.TxPayQueryBalanceRequest
	TxPayQueryInternalBalanceResponse      = txpay.TxPayQueryInternalBalanceResponse
	TxPayQueryOrderRequest                 = txpay.TxPayQueryOrderRequest
	TxPayQueryOrderResponse                = txpay.TxPayQueryOrderResponse
	TxProxyPayOrderRequest                 = txpay.TxProxyPayOrderRequest
	TxProxyPayOrderResponse                = txpay.TxProxyPayOrderResponse
	TxProxyPayQueryInternalBalanceRequest  = txpay.TxProxyPayQueryInternalBalanceRequest
	TxProxyPayQueryInternalBalanceResponse = txpay.TxProxyPayQueryInternalBalanceResponse
	TxProxyPayQueryRequest                 = txpay.TxProxyPayQueryRequest
	TxProxyPayQueryResponse                = txpay.TxProxyPayQueryResponse

	TxPay interface {
		TxPayOrder(ctx context.Context, in *TxPayOrderRequest, opts ...grpc.CallOption) (*TxPayOrderResponse, error)
		TxPayOrderQuery(ctx context.Context, in *TxPayQueryOrderRequest, opts ...grpc.CallOption) (*TxPayQueryOrderResponse, error)
		TxPayQueryBalance(ctx context.Context, in *TxPayQueryBalanceRequest, opts ...grpc.CallOption) (*TxPayQueryInternalBalanceResponse, error)
		TxProxyPayOrder(ctx context.Context, in *TxProxyPayOrderRequest, opts ...grpc.CallOption) (*TxProxyPayOrderResponse, error)
		TxProxyPayOrderQuery(ctx context.Context, in *TxProxyPayQueryRequest, opts ...grpc.CallOption) (*TxProxyPayQueryResponse, error)
		TxProxyPayQueryBalance(ctx context.Context, in *TxProxyPayQueryInternalBalanceRequest, opts ...grpc.CallOption) (*TxProxyPayQueryInternalBalanceResponse, error)
	}

	defaultTxPay struct {
		cli zrpc.Client
	}
)

func NewTxPay(cli zrpc.Client) TxPay {
	return &defaultTxPay{
		cli: cli,
	}
}

func (m *defaultTxPay) TxPayOrder(ctx context.Context, in *TxPayOrderRequest, opts ...grpc.CallOption) (*TxPayOrderResponse, error) {
	client := txpay.NewTxPayClient(m.cli.Conn())
	return client.TxPayOrder(ctx, in, opts...)
}

func (m *defaultTxPay) TxPayOrderQuery(ctx context.Context, in *TxPayQueryOrderRequest, opts ...grpc.CallOption) (*TxPayQueryOrderResponse, error) {
	client := txpay.NewTxPayClient(m.cli.Conn())
	return client.TxPayOrderQuery(ctx, in, opts...)
}

func (m *defaultTxPay) TxPayQueryBalance(ctx context.Context, in *TxPayQueryBalanceRequest, opts ...grpc.CallOption) (*TxPayQueryInternalBalanceResponse, error) {
	client := txpay.NewTxPayClient(m.cli.Conn())
	return client.TxPayQueryBalance(ctx, in, opts...)
}

func (m *defaultTxPay) TxProxyPayOrder(ctx context.Context, in *TxProxyPayOrderRequest, opts ...grpc.CallOption) (*TxProxyPayOrderResponse, error) {
	client := txpay.NewTxPayClient(m.cli.Conn())
	return client.TxProxyPayOrder(ctx, in, opts...)
}

func (m *defaultTxPay) TxProxyPayOrderQuery(ctx context.Context, in *TxProxyPayQueryRequest, opts ...grpc.CallOption) (*TxProxyPayQueryResponse, error) {
	client := txpay.NewTxPayClient(m.cli.Conn())
	return client.TxProxyPayOrderQuery(ctx, in, opts...)
}

func (m *defaultTxPay) TxProxyPayQueryBalance(ctx context.Context, in *TxProxyPayQueryInternalBalanceRequest, opts ...grpc.CallOption) (*TxProxyPayQueryInternalBalanceResponse, error) {
	client := txpay.NewTxPayClient(m.cli.Conn())
	return client.TxProxyPayQueryBalance(ctx, in, opts...)
}
