// Code generated by goctl. DO NOT EDIT.
package types

type TxPayOrderRequest struct {
	OrderNo           string `json:"orderNo"`
	PayType           string `json:"payType"`
	TransactionAmount string `json:"transactionAmount"`
	BankCode          string `json:"bankCode"`
	PageUrl           string `json:"pageUrl"`
	OrderName         string `json:"orderName"`
	MerchantId        string `json:"merchantId"`
	Currency          string `json:"currency"`
	SourceIp          string `json:"sourceIp"`
	UserId            string `json:"userId"`
	JumpType          string `json:"jumpType"`
}

type TxPayOrderQueryRequest struct {
	OrderNo        string `json:"orderNo"`
	ChannelOrderNo string `json:"channelOrderNo"`
}

type Empty struct {
}

type OrderResponse struct {
	Code    string      `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type TxPayQueryInternalBalanceResponse struct {
	ChannelName     string `json:"channelName"`
	ChannelCoding   string `json:"channelCoding"`
	WithdrawBalance string `json:"withdrawBalance"`
	ProxyPayBalance string `json:"proxyPayBalance"`
	UpdateTime      string `json:"updateTime"`
	ErrorCode       string `json:"errorCode, omitempty"`
	ErrorMsg        string `json:"errorMsg, omitempty"`
}

type TxProxyPayOrderRequest struct {
	OrderNo              string `json:"orderNo" valiate: "required"`
	TransactionType      string `json:"transactionType" valiate: "required"`
	TransactionAmount    string `json:"transactionAmount" valiate: "required"`
	ReceiptAccountNumber string `json:"receiptAccountNumber, optional"`
	ReceiptAccountName   string `json:"receiptAccountName, optional"`
	ReceiptCardProvince  string `json:"receiptCardProvince, optional"`
	ReceiptCardCity      string `json:"receiptCardCity, optional"`
	ReceiptCardArea      string `json:"receiptCardArea, optional"`
	ReceiptCardBranch    string `json:"receiptCardBranch, optional"`
	ReceiptCardBankCode  string `json:"receiptCardBankCode, optional"`
	ReceiptCardBankName  string `json:"receiptCardBankName, optional"`
}

type TxProxyPayOrderQueryRequest struct {
	OrderNo        string `json:"orderNo"`
	ChannelOrderNo string `json:"channelOrderNo"`
}

type TxProxyPayQueryInternalBalanceResponse struct {
	ChannelName     string `json:"channelName"`
	ChannelCoding   string `json:"channelCoding"`
	WithdrawBalance string `json:"withdrawBalance"`
	ProxyPayBalance string `json:"proxyPayBalance"`
	UpdateTime      string `json:"updateTime"`
	ErrorCode       string `json:"errorCode"`
	ErrorMsg        string `json:"errorMsg"`
}

type ProxyPayCallBackRequest struct {
}

type PayCallBackRequest struct {
}
